services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - type: bind
        source: .
        target: /home/vscode/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"